/// name : "Albedo"
/// vision : "Geo"
/// weapon : "Sword"
/// nation : "Mondstadt"
/// affiliation : "Knights of Favonius"
/// rarity : 5
/// constellation : "Princeps Cretaceus"
/// birthday : "0000-09-13"
/// description : "A genius known as the Kreideprinz, he is the Chief Alchemist and Captain of the Investigation Team of the Knights of Favonius."
/// skillTalents : [{"name":"Favonius Bladework - Weiss","unlock":"Normal Attack","description":"Normal Attack\nPerform up to 5 rapid strikes.\nCharged Attack\nConsumes a certain amount of Stamina to unleash 2 rapid sword strikes.\nPlunging Attack\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.","type":"NORMAL_ATTACK"},{"name":"Abiogenesis: Solar Isotoma","unlock":"Elemental Skill","description":"Albedo creates a Solar Isotoma using alchemy, which deals AoE Geo DMG on appearance.\nSolar Isotoma\n\nWhen enemies within the Solar Isotoma zone are hit, the Solar Isotoma will generate Transient Blossoms which deal AoE Geo DMG. DMG dealt scales off Albedo's DEF.\nTransient Blossoms can only be generated once every 2s.\nWhen a character is located at the locus of the Solar Isotoma, the Solar Isotoma will accumulate Geo power to form a crystallized platform that lifts the character up to a certain height. Only one crystallized platform can exist at a time.\nSolar Isotoma is considered a Geo construct.\n\nHold to designate the location of the skill.","type":"ELEMENTAL_SKILL"},{"name":"Rite of Progeniture: Tectonic Tide","unlock":"Elemental Burst","description":"Under Albedo's command, Geo crystals surge and burst forth, dealing AoE Geo DMG in front of him.\nIf a Solar Isotoma created by Albedo himself is on the field, 7 Fatal Blossoms will be generated in the Solar Isotoma field, bursting violently into bloom and dealing AoE Geo DMG\nTecotonic Tide DMG and Fatal Blossom DMG will not generate Transient Blossoms.","type":"ELEMENTAL_BURST"}]
/// passiveTalents : [{"name":"Calcite Might","unlock":"Unlocked at Ascension 1","description":"Transient Blossoms generated by Abiogenesis: Solar Isotoma deal 25% more DMG to enemies whose HP is below 50%.","level":1},{"name":"Homuncular Nature","unlock":"Unlocked at Ascension 4","description":"Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by 125 for 10s.","level":4},{"name":"Flash of Genius","unlock":"Unlocked Automatically","description":"When Albedo crafts Weapon Ascension Materials, he has a 10% chance to receive double the product."}]
/// constellations : [{"name":"Flower of Eden","unlock":"Constellation Lv. 1","description":"Transient Blossoms generated by Albedo's Abiogenesis: Solar Isotoma regenerate 1.2 Energy for Albedo.","level":1},{"name":"Opening of Phanerozoic","unlock":"Constellation Lv. 2","description":"Transient Blossoms generated by Abiogenesis: Solar Isotoma grant Albedo Fatal Reckoning for 30s:\n\nEach stack of Fatal Reckoning increases DMG by of Albedo's DEF.\nThe effect stacks up to 4 times.\n\nUnleashing Rite of Progeniture: Tectonic Tide consumes all stacks of Fatal Reckoning, increasing the DMG dealt by the Tectonic Tide and Fatal Blossoms based on the number of stacks consumed.","level":2},{"name":"Grace of Helios","unlock":"Constellation Lv. 3","description":"Increases the level of Abiogenesis: Solar Isotoma by 3.\nMaximum upgrade level is 15.","level":3},{"name":"Descent of Divinity","unlock":"Constellation Lv. 4","description":"Solar Isotoma increases Plunging Attack DMG by 30% for active party members within the AoE.","level":4},{"name":"Tide of Hadaen","unlock":"Constellation Lv. 5","description":"Increases the level of Rite of Progeniture: Tectonic Tide by 3.\nMaximum upgrade level is 15.","level":5},{"name":"Dust of Purification","unlock":"Constellation Lv. 6","description":"If active party members within the AoE are protected by a shield created by Crystallize, Solar Isotoma increases their DMG by 17%.","level":6}]
/// vision_key : "GEO"
/// weapon_type : "SWORD"

class CharacterDetailModel {
  CharacterDetailModel({
      String? name, 
      String? vision, 
      String? weapon, 
      String? nation, 
      String? affiliation, 
      int? rarity, 
      String? constellation, 
      String? birthday, 
      String? description, 
      List<SkillTalents>? skillTalents, 
      List<PassiveTalents>? passiveTalents, 
      List<Constellations>? constellations, 
      String? visionKey, 
      String? weaponType,}){
    _name = name;
    _vision = vision;
    _weapon = weapon;
    _nation = nation;
    _affiliation = affiliation;
    _rarity = rarity;
    _constellation = constellation;
    _birthday = birthday;
    _description = description;
    _skillTalents = skillTalents;
    _passiveTalents = passiveTalents;
    _constellations = constellations;
    _visionKey = visionKey;
    _weaponType = weaponType;
}

  CharacterDetailModel.fromJson(dynamic json) {
    _name = json['name'];
    _vision = json['vision'];
    _weapon = json['weapon'];
    _nation = json['nation'];
    _affiliation = json['affiliation'];
    _rarity = json['rarity'];
    _constellation = json['constellation'];
    _birthday = json['birthday'];
    _description = json['description'];
    if (json['skillTalents'] != null) {
      _skillTalents = [];
      json['skillTalents'].forEach((v) {
        _skillTalents?.add(SkillTalents.fromJson(v));
      });
    }
    if (json['passiveTalents'] != null) {
      _passiveTalents = [];
      json['passiveTalents'].forEach((v) {
        _passiveTalents?.add(PassiveTalents.fromJson(v));
      });
    }
    if (json['constellations'] != null) {
      _constellations = [];
      json['constellations'].forEach((v) {
        _constellations?.add(Constellations.fromJson(v));
      });
    }
    _visionKey = json['vision_key'];
    _weaponType = json['weapon_type'];
  }
  String? _name;
  String? _vision;
  String? _weapon;
  String? _nation;
  String? _affiliation;
  int? _rarity;
  String? _constellation;
  String? _birthday;
  String? _description;
  List<SkillTalents>? _skillTalents;
  List<PassiveTalents>? _passiveTalents;
  List<Constellations>? _constellations;
  String? _visionKey;
  String? _weaponType;
CharacterDetailModel copyWith({  String? name,
  String? vision,
  String? weapon,
  String? nation,
  String? affiliation,
  int? rarity,
  String? constellation,
  String? birthday,
  String? description,
  List<SkillTalents>? skillTalents,
  List<PassiveTalents>? passiveTalents,
  List<Constellations>? constellations,
  String? visionKey,
  String? weaponType,
}) => CharacterDetailModel(  name: name ?? _name,
  vision: vision ?? _vision,
  weapon: weapon ?? _weapon,
  nation: nation ?? _nation,
  affiliation: affiliation ?? _affiliation,
  rarity: rarity ?? _rarity,
  constellation: constellation ?? _constellation,
  birthday: birthday ?? _birthday,
  description: description ?? _description,
  skillTalents: skillTalents ?? _skillTalents,
  passiveTalents: passiveTalents ?? _passiveTalents,
  constellations: constellations ?? _constellations,
  visionKey: visionKey ?? _visionKey,
  weaponType: weaponType ?? _weaponType,
);
  String? get name => _name;
  String? get vision => _vision;
  String? get weapon => _weapon;
  String? get nation => _nation;
  String? get affiliation => _affiliation;
  int? get rarity => _rarity;
  String? get constellation => _constellation;
  String? get birthday => _birthday;
  String? get description => _description;
  List<SkillTalents>? get skillTalents => _skillTalents;
  List<PassiveTalents>? get passiveTalents => _passiveTalents;
  List<Constellations>? get constellations => _constellations;
  String? get visionKey => _visionKey;
  String? get weaponType => _weaponType;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = _name;
    map['vision'] = _vision;
    map['weapon'] = _weapon;
    map['nation'] = _nation;
    map['affiliation'] = _affiliation;
    map['rarity'] = _rarity;
    map['constellation'] = _constellation;
    map['birthday'] = _birthday;
    map['description'] = _description;
    if (_skillTalents != null) {
      map['skillTalents'] = _skillTalents?.map((v) => v.toJson()).toList();
    }
    if (_passiveTalents != null) {
      map['passiveTalents'] = _passiveTalents?.map((v) => v.toJson()).toList();
    }
    if (_constellations != null) {
      map['constellations'] = _constellations?.map((v) => v.toJson()).toList();
    }
    map['vision_key'] = _visionKey;
    map['weapon_type'] = _weaponType;
    return map;
  }

}

/// name : "Flower of Eden"
/// unlock : "Constellation Lv. 1"
/// description : "Transient Blossoms generated by Albedo's Abiogenesis: Solar Isotoma regenerate 1.2 Energy for Albedo."
/// level : 1

class Constellations {
  Constellations({
      String? name, 
      String? unlock, 
      String? description, 
      int? level,}){
    _name = name;
    _unlock = unlock;
    _description = description;
    _level = level;
}

  Constellations.fromJson(dynamic json) {
    _name = json['name'];
    _unlock = json['unlock'];
    _description = json['description'];
    _level = json['level'];
  }
  String? _name;
  String? _unlock;
  String? _description;
  int? _level;
Constellations copyWith({  String? name,
  String? unlock,
  String? description,
  int? level,
}) => Constellations(  name: name ?? _name,
  unlock: unlock ?? _unlock,
  description: description ?? _description,
  level: level ?? _level,
);
  String? get name => _name;
  String? get unlock => _unlock;
  String? get description => _description;
  int? get level => _level;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = _name;
    map['unlock'] = _unlock;
    map['description'] = _description;
    map['level'] = _level;
    return map;
  }

}

/// name : "Calcite Might"
/// unlock : "Unlocked at Ascension 1"
/// description : "Transient Blossoms generated by Abiogenesis: Solar Isotoma deal 25% more DMG to enemies whose HP is below 50%."
/// level : 1

class PassiveTalents {
  PassiveTalents({
      String? name, 
      String? unlock, 
      String? description, 
      int? level,}){
    _name = name;
    _unlock = unlock;
    _description = description;
    _level = level;
}

  PassiveTalents.fromJson(dynamic json) {
    _name = json['name'];
    _unlock = json['unlock'];
    _description = json['description'];
    _level = json['level'];
  }
  String? _name;
  String? _unlock;
  String? _description;
  int? _level;
PassiveTalents copyWith({  String? name,
  String? unlock,
  String? description,
  int? level,
}) => PassiveTalents(  name: name ?? _name,
  unlock: unlock ?? _unlock,
  description: description ?? _description,
  level: level ?? _level,
);
  String? get name => _name;
  String? get unlock => _unlock;
  String? get description => _description;
  int? get level => _level;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = _name;
    map['unlock'] = _unlock;
    map['description'] = _description;
    map['level'] = _level;
    return map;
  }

}

/// name : "Favonius Bladework - Weiss"
/// unlock : "Normal Attack"
/// description : "Normal Attack\nPerform up to 5 rapid strikes.\nCharged Attack\nConsumes a certain amount of Stamina to unleash 2 rapid sword strikes.\nPlunging Attack\nPlunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact."
/// type : "NORMAL_ATTACK"

class SkillTalents {
  SkillTalents({
      String? name, 
      String? unlock, 
      String? description, 
      String? type,}){
    _name = name;
    _unlock = unlock;
    _description = description;
    _type = type;
}

  SkillTalents.fromJson(dynamic json) {
    _name = json['name'];
    _unlock = json['unlock'];
    _description = json['description'];
    _type = json['type'];
  }
  String? _name;
  String? _unlock;
  String? _description;
  String? _type;
SkillTalents copyWith({  String? name,
  String? unlock,
  String? description,
  String? type,
}) => SkillTalents(  name: name ?? _name,
  unlock: unlock ?? _unlock,
  description: description ?? _description,
  type: type ?? _type,
);
  String? get name => _name;
  String? get unlock => _unlock;
  String? get description => _description;
  String? get type => _type;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['name'] = _name;
    map['unlock'] = _unlock;
    map['description'] = _description;
    map['type'] = _type;
    return map;
  }

}